name: Build and Deploy to External Repository

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Deploy to external repository
        env:
          DIST_DIR: dist
        run: |
          cd $DIST_DIR
          git remote add origin https://onaniishoujo:{{ secret.DEPLOY_PRIVATE_KEY }}@github.com/onaniishoujo/onaniishoujo.github.io.git
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy from GitHub Actions: ${{ github.sha }}"
          git push --force origin gh-pages
